#The Range of Existing Frame Searching When Generating Nether Portal
#Range: 32 ~ 1000
portal_searching_range = 128
#Longer Hand Reach In Creative
long_reach_in_creative = true
#Load Remote Chunks Actively
actively_load_remote_chunks = true
#Teleportation Debug
teleportation_debug = false
#Load Fewer Chunks
load_fewer_chunks = true
#Multi Threaded Nether Portal Searching
multi_threaded_nether_portal_searching = true
#Loose Serve Side Anti Hack Movement Check
loose_movement_check = false
#See the Wiki to Know How to Configure it
custom_portal_frame = "minecraft:overworld,8,midnight:midnight,1,minecraft:bone_block\nminecraft:overworld,1,the_bumblezone:bumblezone,1,minecraft:honeycomb_block"

